name: 'Pandoc Document Converter'
description: 'GitHub Action to Convert Documents via Pandoc'
author: 'Max Held'
inputs:
  pandoc-args:
    description: 'Arguments to pass to Pandoc, including input and output files'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'docker://pandoc/latex:2.7.3'
  entrypoint: sh
  args:
    - " -c "
    - " /usr/bin/pandoc ${{ inputs.pandoc-args }} "
branding:
  icon: 'book-open'  
  color: 'green'
