name: 'Pandoc Document Converter'
description: 'GitHub Action to Convert Documents via Pandoc'
author: 'Max Held'
runs:
  using: 'docker'
  image: 'docker://pandoc/latex:2.7.3'
  entrypoint: sh
  args:
    - " -c "
    - " /usr/bin/pandoc ${{ inputs.pandoc-args }} "
branding:
  icon: 'book-open'  
  color: 'green'
